spring:
      #数据库相关的配置
      datasource:
#        url: jdbc:mysql://10.82.0.182:3306/trff?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
        username: root
        password: 451179
liquibase:
  enabled: true
  change-log: classpath:/config/liquibase/master_changelog.xml
